@startuml

title __SRC's Class Diagram__\n

    abstract class Canard {
        {abstract} + afficher()
        + cancaner()
        + nager()
        + voler()
    }

    class CanardEnPlastique {
        + CanardEnPlastique()
        + afficher()
    }

    class Colvert {
        + Colvert()
        + afficher()
    }

    class SuperCanard {
        {static} + main()
    }

    class SuperCanardTest {
        {static} ~ bilanAssertions : int
        ~ clavierProgrammeATester : BufferedWriter
        ~ ecranProgrammeATester : BufferedReader
        ~ executionProgrammeATester : Process
        ~ finDeLigne : String
        {static} ~ programmeATester : String
        {static} ~ totalAssertions : int
        {static} + main()
        + test_ligne1()
        + test_ligne2()
        + test_ligne3()
        + test_ligne4()
        # setUp()
    }

    class SuperCanardTest2 {
        - oldStream : PrintStream
        - outContent : ByteArrayOutputStream
        + cleanUpStreams()
        + setUpStreams()
        + testComportementCanardEnPlastique()
        + testComportementColvert()
        - readLine()
    }

      abstract class strategies.fly.FlyStrategy {
          {abstract} + voler()
      }


      class strategies.fly.FlyingBehavior {
          + voler()
      }



      class strategies.fly.NoFlyBehavior {
          + voler()
      }


  strategies.fly.FlyingBehavior -up-|> strategies.fly.FlyStrategy
  strategies.fly.NoFlyBehavior -up-|> strategies.fly.FlyStrategy


      class strategies.sound.CancaneSoundBehavior {
          + cancaner()
      }



      abstract class strategies.sound.SoundStrategy {
          {abstract} + cancaner()
      }



  strategies.sound.CancaneSoundBehavior -up-|> strategies.sound.SoundStrategy


      class strategies.swim.SwimmingBehavior {
          + nager()
      }

      abstract class strategies.swim.SwimStrategy {
          {abstract} + nager()
    }

  strategies.swim.SwimmingBehavior -up-|> strategies.swim.SwimStrategy

  Canard o-- strategies.fly.FlyStrategy : flyStrategy
  Canard o-- strategies.sound.SoundStrategy : soundStrategy
  Canard o-- strategies.swim.SwimStrategy : swimStrategy
  CanardEnPlastique -up-|> Canard
  Colvert -up-|> Canard
  SuperCanardTest -up-|> junit.framework.TestCase


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
