@startuml

title __SUPERCANARDBOF's Class Diagram__\n

abstract class application.Canard {
      {abstract} + afficher()
      + cancaner()
      + nager()
      + voler()
  }



  class application.CanardEnPlastique {
      + CanardEnPlastique()
      + afficher()
  }



  class application.Colvert {
      + Colvert()
      + afficher()
  }

  class strategies.cancaner.impl.CanardMuet {
          + cancaner()
      }


  class strategies.cancaner.impl.Cancan {
      + cancaner()
  }



  class strategies.cancaner.impl.Coincoin {
      + cancaner()
  }

   interface strategies.cancaner.Cancaner {
       {abstract} + cancaner()
   }

   class strategies.volter.impl.Fly {
           + voler()
   }



   class strategies.volter.impl.NotFly {
       + voler()
   }

   interface strategies.volter.Volter {
       {abstract} + voler()
   }

   class tests.SuperCanardTest {
         {static} ~ bilanAssertions : int
         ~ clavierProgrammeATester : BufferedWriter
         ~ ecranProgrammeATester : BufferedReader
         ~ executionProgrammeATester : Process
         ~ finDeLigne : String
         {static} ~ programmeATester : String
         {static} ~ totalAssertions : int
         {static} + main()
         + test_ligne1()
         + test_ligne2()
         + test_ligne3()
         + test_ligne4()
         # setUp()
     }


   class tests.SuperCanardTest2 {
         - oldStream : PrintStream
         - outContent : ByteArrayOutputStream
         + cleanUpStreams()
         + setUpStreams()
         + testComportementCanardEnPlastique()
         + testComportementColvert()
         - readLine()
   }

   class application.application.SuperCanard {
          {static} + main()
    }
  

  application.Canard o-- strategies.volter.Volter : flying
  application.Canard o-- strategies.cancaner.Cancaner : singing
  application.CanardEnPlastique -up-|> application.Canard
  application.Colvert -up-|> application.Canard
  strategies.cancaner.impl.CanardMuet .up.|> strategies.cancaner.Cancaner
  strategies.cancaner.impl.Cancan .up.|> strategies.cancaner.Cancaner
  strategies.cancaner.impl.Coincoin .up.|> strategies.cancaner.Cancaner
  strategies.volter.impl.Fly .up.|> strategies.volter.Volter
  strategies.volter.impl.NotFly .up.|> strategies.volter.Volter
  tests.SuperCanardTest -up-|> junit.framework.TestCase


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
