@startuml

title __OBSERVER's Class Diagram__\n

  namespace nonpattern {
    class nonpattern.CourseViewer {
    }
  }
  

  namespace observer {
    class observer.CourseRecord {
    }
  }
  

  namespace observer {
    class observer.LayoutConstants {
    }
  }
  

  namespace pattern {
    class pattern.BarChartObserver {
    }
  }
  

  namespace pattern {
    class pattern.CourseController {
    }
  }
  

  namespace pattern {
    class pattern.CourseData {
    }
  }
  

  namespace pattern {
    abstract class pattern.Observable {
    }
  }
  

  namespace pattern {
    interface pattern.Observer {
    }
  }
  

  namespace pattern {
    class pattern.PieChartObserver {
    }
  }
  

  namespace tmp {
    class tmp.A {
    }
  }
  

  namespace tmp {
    class tmp.B {
    }
  }
  

  nonpattern.CourseViewer .up.|> java.awt.event.ActionListener
  nonpattern.CourseViewer .up.|> javax.swing.event.ChangeListener
  nonpattern.CourseViewer -up-|> javax.swing.JFrame
  pattern.BarChartObserver .up.|> pattern.Observer
  pattern.BarChartObserver -up-|> javax.swing.JPanel
  pattern.CourseController .up.|> java.awt.event.ActionListener
  pattern.CourseController .up.|> javax.swing.event.ChangeListener
  pattern.CourseController .up.|> pattern.Observer
  pattern.CourseController -up-|> javax.swing.JPanel
  pattern.CourseController o-- pattern.CourseData : courseData
  pattern.CourseData -up-|> pattern.Observable
  pattern.PieChartObserver .up.|> pattern.Observer
  pattern.PieChartObserver -up-|> javax.swing.JPanel
  tmp.B o-- tmp.A : myA


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
