@startuml

'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------

hide circle
hide empty members
hide empty methods


class Square {
  int width
}

class Rectangle extends Square {
  int length
}

legend right
  <i>A rectangle is a square with an additional dimension...</i>
endlegend

@enduml
